/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Michi' at '26.03.17 18:56' with Gradle 2.13
 *
 * @author Michi, @date 26.03.17 18:56
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
